Project4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('second_hand_clothes_app/', include('second_hand_clothes_app.urls', namespace='second_hand_clothes_app')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

second_hand_clothes_app/urls.py
from django.urls import path
from . import views
app_name = 'second_hand_clothes_app'
urlpatterns = [
    #clothes views
    path('', views.clothes_index, name="clothes_index"),
    path('list/', views.clothes_list, name="clothes_list"),
    path('list/sort_by_price', views.clothes_sort, name="clothes_sort"),
    path('list/add_comment', views.clothes_add_comment, name="clothes_add_comment"),
    path('list/delete_comment', views.clothes_delete_comment, name="clothes_delete_comment"),
    path('list/<int:item_id>', views.clothes_detail, name="clothes_detail"),
    path('list/<int:item_id>/edit', views.clothes_edit, name="clothes_edit"),
    path('list/<int:item_id>/delete', views.clothes_delete, name="clothes_delete"),
    path('add_item/', views.clothes_add_item, name="clothes_add_item"),
    path('search_result/', views.clothes_search_result, name="clothes_search_result"),
    path('sign_in/', views.clothes_sign_in, name="clothes_sign_in"),
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    #clothes views
    path('register', views.register, name="register"),
    path('profile/<str:username>', views.profile, name="profile"),
    path('edit_profile/<str:username>', views.edit_profile, name="edit_profile"),
    path('sign_in_action', views.login_user, name="sign_in"),
    path('log_out/', views.logout_user, name="log_out"),
]

second_hand_clothes_app/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class ClothesList(models.Model):
    name = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='image/')
    price = models.IntegerField(default=0)
    seller = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    size = models.CharField(max_length=200)
    comment = ArrayField(models.TextField(blank=True), blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('second_hand_clothes_app:clothes_detail', args=[self.id])

regular_user = {"username": "regular", "password": "regular"}
admin_user = {"username": "admin", "password": "admin"}

        
    

second_hand_clothes_app/views.py
from django.shortcuts import render, redirect
from .models import regular_user, admin_user, ClothesList, User
from django.http import JsonResponse
from django.contrib import messages
from actions.models import Action
from comments.models import Comment
from django.core import serializers
from django.urls import reverse
from django.contrib.humanize.templatetags.humanize import naturaltime

# Create your views here.
def clothes_index(request):
    clothes = ClothesList.objects.all()
    actions = Action.objects.all().order_by('-created_time')
    return render(request,"second_hand_clothes_app/clothes/index.html", {'clothes': clothes, 'actions':actions})

def clothes_list(request):
    clothes = ClothesList.objects.all()
    
    context = {'clothes': clothes}
    return render(request,"second_hand_clothes_app/clothes/list.html", context) 

def clothes_sort(request):
    clothes = ClothesList.objects.all().order_by('price')
    
    context = {'clothes': clothes, 'order_by': 'price'}
    return render(request,"second_hand_clothes_app/clothes/list.html", context) 

def clothes_detail(request, item_id):
    clothes = ClothesList.objects.all()
    for clothes_item in clothes:
        if clothes_item.id == item_id:
            break
    user = User.objects.get(username=clothes_item.seller)
    username = request.session.get("username")
    comments = Comment.objects.all().filter(user_id=user.id).order_by('-created_time')
    return render(request,"second_hand_clothes_app/clothes/detail.html", {"clothes_item":clothes_item, "comments":comments}) 

def clothes_add_item(request):

    if request.method == 'POST':
        name = request.POST.get('name')
        picture = request.FILES.get('image')
        size = request.POST.get('size')
        price = request.POST.get('price')
        des = request.POST.get('description')

        user = User.objects.get(username=request.session.get("username"))

        cl = ClothesList(
            name = name,
            seller = request.session.get('username'),
            picture = picture,
            size = size,
            price = price,
            description = des,
            comment = [],
            user=user,
        )
        cl.save()

        #log the action
        action = Action(
            user = user,
            verb = "create the item",
            target = cl,
        )
        action.save()

        messages.add_message(request, messages.SUCCESS, "You successfully submitted the clothes: %s" % cl.name)
        return redirect('second_hand_clothes_app:clothes_detail', cl.id)
    else:
        return render(request,"second_hand_clothes_app/clothes/add_item.html")

def clothes_edit(request, item_id):
    if request.method == 'POST':
        name = request.POST.get('name')
        picture = request.FILES.get('image')
        size = request.POST.get('size')
        price = request.POST.get('price')
        des = request.POST.get('description')
        user = User.objects.get(username=request.session.get("username"))

        try:
            clothes = ClothesList.objects.get(pk=item_id)
            clothes.name = name
            clothes.size = size
            clothes.price = price
            clothes.description = des
            if picture:
                clothes.picture = picture
            clothes.save()

            #log the action
            action = Action(
                user = user,
                verb = "edit the item",
                target = clothes,
            )
            action.save()

            messages.add_message(request, messages.INFO, "You successfully edited the clothes: %s" % clothes.name)
            return redirect('second_hand_clothes_app:clothes_detail', clothes.id)
        except ClothesList.DoesNotExist:
            return redirect('second_hand_clothes_app:clothes_index')
    else:
        clothes = ClothesList.objects.all()
        for item in clothes:
            if item.id == item_id:
                break
        return render(request,"second_hand_clothes_app/clothes/edit.html", {"item": item})

def clothes_delete(request, item_id):
    user = User.objects.get(username=request.session.get("username"))
    clothes = ClothesList.objects.get(pk=item_id)
    ClothesList.objects.get(pk=item_id).delete()
    action = Action(
        user = user,
        verb = "delete the item",
        target = clothes,
    )
    action.save()
    messages.add_message(request, messages.WARNING, "You successfully deleted the clothes: %s" % clothes.name)
    return redirect('second_hand_clothes_app:clothes_list')



# def clothes_show_comment(request):
#     is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
#     if is_ajax and request.method == "POST":
#         clothes_id = request.POST.get('clothes_id')
#         clothes = ClothesList.objects.get(pk=clothes_id)
        # user = User.objects.get(username=clothes.seller)
        # try:
        #     comments_json = serializers.serialize("json", Comment.objects.all().filter(user_id=user.id))
        #     username = request.session.get("username")
        #     url = reverse('users:profile', args=[username])

        #     return JsonResponse({'success': 'success', 'comment': comments_json, 'url': url}, status=200)
        # except ClothesList.DoesNotExist:
        #     return JsonResponse({'error': 'No clothes found with that ID'}, status=200)
#     else:
#         return JsonResponse({'error': 'Invalid Ajax request'}, status=400)

def clothes_add_comment(request):
    user1 = User.objects.get(username=request.session.get("username"))
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        clothes_id = request.POST.get('clothes_id')
        clothes_comment = request.POST.get('clothes_comment')
        clothes = ClothesList.objects.get(pk=clothes_id)
        user = User.objects.get(username=clothes.seller)
        if clothes_comment != "":
            try:
                # clothes = ClothesList.objects.get(pk=clothes_id)
                cm = Comment(
                    user = user,
                    comment = clothes_comment,
                    username = request.session.get("username"),
                )
                cm.save()

                action = Action(
                    user = user1,
                    verb = "add a comment to the item",
                    target = clothes,
                )
                action.save()
                url = reverse('users:profile', args=[request.session.get("username")])
                time = naturaltime(cm.created_time)

                return JsonResponse({'success': 'success', 'comment': clothes_comment, 'url': url, 'username': request.session.get("username"), 'time':time, 'id': cm.id}, status=200)
            except ClothesList.DoesNotExist:
                return JsonResponse({'error': 'No clothes found with that ID'}, status=200)
        else:
            return JsonResponse({'error': 'No comment'}, status=200)    
    else:
        return JsonResponse({'error': 'Invalid Ajax request'}, status=400)

def clothes_delete_comment(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        comment_id = request.POST.get('comment_id')
        comment = Comment.objects.get(pk=comment_id)
        try:
            comment.delete()
            return JsonResponse({'success': 'success', 'id': comment_id}, status=200)
        except Comment.DoesNotExist:
            return JsonResponse({'error': 'No clothes found with that ID'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax request'}, status=400)


def clothes_search_result(request):
    return render(request,"second_hand_clothes_app/clothes/search-results.html")

def clothes_sign_in(request):
    return render(request,"second_hand_clothes_app/clothes/sign_in.html")

templates/second_hand_clothes_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css-box %}{% endblock %}
    <title>Second Hand Clothes | {% block page-title %}{% endblock %}</title>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</head>

<body>
    <div id="header">
        <div id="title-box">

            <div id="logo-box">
                <img src="{% static 'pictures/VTlogo.png' %}" alt="Logo">
                <h5>VT Second Hand Clothes</h5>
            </div><!-- #logo-box -->

            <div id="login-box">
                <img id="bar" src="{% static 'pictures/bar.svg' %}" alt="bar">
                {% if request.session.username %}
                <a href="{% url 'users:log_out' %}"><img id="sign_out" src="{% static 'pictures/sign-out.svg' %}"
                        alt="signout"></a>
                {% endif %}
                <img id="search-image" src="{% static 'pictures/search.svg' %}" alt="search">
                <form class="search-form" action="{% url 'second_hand_clothes_app:clothes_search_result' %}" method="GET">
                    <input class="search-input" type="text" id="search" name="search-clothes" placeholder="Search clothes">
                    <input class="go-button" type="submit" name="search" value="Go">
                </form>
                <img src="{% static 'pictures/cart.png' %}" alt="cart">
                <a href="{% url 'users:register' %}"> Register </a>
                {% if request.session.username %}
                <p>Hi, <a href="{% url 'users:profile' request.session.username %}">{{request.session.username}}</a></p>
                {% else %}
                <a href="{% url 'second_hand_clothes_app:clothes_sign_in' %}">log In</a>
                {% endif %}

                <!-- {% block login-box %}{% endblock %} -->

            </div><!-- #login-box -->

        </div><!-- #title-box -->

        <ul id="primary-nav">
            <li><a href="{% url 'second_hand_clothes_app:clothes_index' %}">Home</a></li>
            <li><a href="{% url 'second_hand_clothes_app:clothes_list' %}">Women</a></li>
            <li><a href="{% url 'second_hand_clothes_app:clothes_add_item' %}">Sell your items</a></li>
        </ul><!-- #navigatiom button -->

    </div><!-- #header -->

    <div id="content">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        
        {% block content %}{% endblock %}

    </div><!-- #content -->


    {% block no-result %}{% endblock%}


    <div id="footer">


        <p id="footer-nav"><a href="{% url 'second_hand_clothes_app:clothes_index' %}">Home</a> | <a
                href="{% url 'second_hand_clothes_app:clothes_list' %}">Women</a> | <a
                href="{% url 'second_hand_clothes_app:clothes_add_item' %}">Sell your items</a></p>
        <!-- #footer-nav -->
    </div><!-- #footer -->

</body>

</html>