Project4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('second_hand_clothes_app/', include('second_hand_clothes_app.urls', namespace='second_hand_clothes_app')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    #clothes views
    path('register', views.register, name="register"),
    path('profile/<str:username>', views.profile, name="profile"),
    path('edit_profile/<str:username>', views.edit_profile, name="edit_profile"),
    path('sign_in_action', views.login_user, name="sign_in"),
    path('log_out/', views.logout_user, name="log_out"),
]

actions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


# Create your models here.
class Action(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    verb = models.CharField(max_length=100)
    target_ct = models.ForeignKey(ContentType, blank=True, null=True, on_delete=models.CASCADE)
    target_id = models.PositiveIntegerField(blank=True, null=True)
    target = GenericForeignKey('target_ct', 'target_id')
    created_time = models.DateTimeField(auto_now_add=True)

templates/actions/action/feed.html
<h3>Recent Activity</h3>

<ul>
{% for action in actions %}

    
    {% if action.verb == "edit the profile" %}
    <li>{{action.user.username}} {{action.verb}} "<a href="{% url 'users:profile' action.user.username %}">{{action.target}}</a>" ({{action.created_time}})</li>
    {% else %}
    <li>{{action.user.username}} {{action.verb}} "<a href="{{action.target.get_absolute_url}}">{{action.target}}</a>" ({{action.created_time}})</li> 
    {% endif %}
        
{% empty %}

    <li>No activity yet.</li>
    
{% endfor %}
</ul>

    