Project4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('second_hand_clothes_app/', include('second_hand_clothes_app.urls', namespace='second_hand_clothes_app')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    #clothes views
    path('register', views.register, name="register"),
    path('profile/<str:username>', views.profile, name="profile"),
    path('edit_profile/<str:username>', views.edit_profile, name="edit_profile"),
    path('sign_in_action', views.login_user, name="sign_in"),
    path('log_out/', views.logout_user, name="log_out"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Detail(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default="regular", max_length=50)
    sex = models.CharField(default="Male", max_length=50)

@receiver(post_save, sender=User)
def create_user_detail(sender, instance, created, **kwargs):
    if created:
        Detail.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_detail(sender, instance, **kwargs):
        instance.detail.save()

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate
from actions.models import Action
from users.models import Detail
# Create your views here.

def profile(request, username):
    user1 = get_object_or_404(User, username=username)
    actions = Action.objects.all().filter(user=user1).order_by('-created_time')
    return render(request,"users/user/profile.html", {"user": user1, "actions":actions})

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        last_name = request.POST.get('lastname')
        first_name = request.POST.get('firstname')
        email = request.POST.get('email')
        password = request.POST.get('password')
        sex = request.POST.get('sex')

        user = User.objects.create_user(username, email, password, last_name=last_name, first_name=first_name)
        detail = Detail.objects.get(user_id=user.id)
        detail.sex = sex
        detail.save()

        request.session['username'] = user.username
        request.session['role'] = user.detail.role
        
        messages.add_message(request, messages.SUCCESS, "You successfully registerd with the username: %s" % user.username)

        return redirect('second_hand_clothes_app:clothes_index')
    else:
        return render(request,"users/user/register.html",)

def edit_profile(request, username):
    if request.method == 'POST':
        last_name = request.POST.get('lastname')
        first_name = request.POST.get('firstname')
        email = request.POST.get('email')
        password = request.POST.get('password')
        sex = request.POST.get('sex')

        try:
            user = get_object_or_404(User, username=username)
            detail = Detail.objects.get(user_id=user.id)
            user.last_name = last_name
            user.first_name = first_name
            user.email = email
            user.password = password
            if request.POST.get('role'):
                detail.role = request.POST.get('role')
                request.session['role'] = user.detail.role
            detail.sex = sex
            detail.save()
            user.save()

            action = Action(
                user = user,
                verb = "edit the profile",
                target = user,
            )
            action.save()

            messages.add_message(request, messages.INFO, "You successfully edited the profile")
            return redirect('users:profile', user.username)
        except User.DoesNotExist:
            return redirect('users:profile', user.username)
    else:
        user1 = get_object_or_404(User, username=username)
        detail1 = Detail.objects.get(user_id=user1.id)
        print(detail1.sex)
        return render(request, "users/user/edit_profile.html", {"user": user1})

def login_user(request):
    username = request.POST.get("username")
    pw = request.POST.get("password")

    user = authenticate(username=username, password=pw)
    if user is not None:
        request.session['username'] = user.username
        request.session['role'] = user.detail.role
        messages.add_message(request, messages.SUCCESS, "You have logged in successfully.")
    else:
        messages.add_message(request, messages.ERROR, "Invalid username or password.")

    return redirect('second_hand_clothes_app:clothes_list')


def logout_user(request):
    del request.session['username']
    del request.session['role']
    return redirect('second_hand_clothes_app:clothes_index')

templates/users/user/edit_profile.html
{% extends "second_hand_clothes_app/base.html" %}
{% load static %}
{% block page-title %} Edit Profile {% endblock %}

{% block content %}
<div class="container my-5 signin">
    <h2>Edit Profile</h2>
    <form action="{% url 'users:edit_profile' user.username %}" method="POST">
        {% csrf_token %}
        <p>* = required</p>
        <div class="mb-3">
            <label for="register-lastname" class="form-label">Last Name*</label>
            <input class="form-control" id="register-lastname" name="lastname" type="text" value="{{user.last_name}}" required>
        </div>
        <div class="mb-3">
            <label for="register-firstname" class="form-label">First Name*</label>
            <input class="form-control" id="register-firstname" name="firstname" type="text" value="{{user.first_name}}" required>
        </div>
        <div class="mb-3">
            <label for="sexual-select" class="form-label">Choose your sex:</label>
            <select class="form-control" name="sex" id="sexual-select" required>
                <option value="">--Please choose an option--</option>
                <option value="Male">Male</option>
                <option value="Female">Female</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="register-email" class="form-label">Email*</label>
            <input class="form-control" id="register-email" name="email" type="email" value="{{user.email}}" required>
        </div>
        <div class="mb-3">
            <label for="register-password" class="form-label">Password*</label>
            <input class="form-control" id="register-password" name="password" type="password" value="{{user.password}}" required>
        </div>

        
        {% if user.detail.role == "admin" %}
        <div class="mb-3">
            <label for="register-role" class="form-label">Role*</label>
            <input class="form-control" id="register-role" name="role" type="text" value="{{user.detail.role}}" required>
        </div>
        {% endif %}
            

        <input class="btn btn-primary" type="submit" name="submit" value="Save">
        
    </form>
</div>
{% endblock %}


{% block css-box %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
    integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'CSS/register.css' %}">
{% endblock %}

templates/users/user/profile.html
{% extends "second_hand_clothes_app/base.html" %}
{% load static %}
{% block page-title %} Profile for {{ user.username }} {% endblock %}



{% block content %}
<div class="container dashboard">
    <div class="row">
        <div class="col-sm-12 col-md-6 dash-col">
            <h1>Profile for {{ user.username }}</h1>
            <dl>
                <dt>Username</dt>
                <dd>{{user.username}}</dd>
                <dt>First name</dt>
                <dd>{{user.first_name}}</dd>
                <dt>Last name</dt>
                <dd>{{user.last_name}}</dd>
                <dt>Sex</dt>
                <dd>{{user.detail.sex}}</dd>
                <dt>Email address</dt>
                <dd>{{user.email}}</dd>
                <dt>Role</dt>
                <dd>{{user.detail.role}}</dd>
            </dl>
            
            {% if request.session.username == user.username or request.session.role == "admin" %}
            <a href="{% url 'users:edit_profile' user.username %}">
                <button class="btn btn-secondary">Edit</button>
            </a>
            {% endif %}
                
        </div>
        <div class="col-sm-12 col-md-6">
            {% include 'actions/action/feed.html' %}
        </div>
    </div>

</div>

{% endblock %}

{% block css-box %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
    integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'CSS/detail.css' %}">
{% endblock %}

templates/users/user/register.html
{% extends "second_hand_clothes_app/base.html" %}
{% load static %}
{% block page-title %} Register Page {% endblock %}

{% block content %}
<div class="container my-5 signin">
    <h2>Register</h2>
    <form action="{% url 'users:register' %}" method="POST">
        {% csrf_token %}
        <p>* = required</p>
        <div class="mb-3">
            <label for="register-username" class="form-label">Username*</label>
            <input class="form-control" id="register-username" name="username" type="text" required>
        </div>
        <div class="mb-3">
            <label for="register-lastname" class="form-label">Last Name*</label>
            <input class="form-control" id="register-lastname" name="lastname" type="text" required>
        </div>
        <div class="mb-3">
            <label for="register-firstname" class="form-label">First Name*</label>
            <input class="form-control" id="register-firstname" name="firstname" type="text" required>
        </div>
        <div class="mb-3">
            <label for="sexual-select" class="form-label">Choose your sex:</label>
            <select class="form-control" name="sex" id="sexual-select" required>
                <option value="">--Please choose an option--</option>
                <option value="Male">Male</option>
                <option value="Female">Female</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="register-email" class="form-label">Email*</label>
            <input class="form-control" id="register-email" name="email" type="email" required>
        </div>
        <div class="mb-3">
            <label for="register-password" class="form-label">Password*</label>
            <input class="form-control" id="register-password" name="password" type="password" required>
        </div>

        <input class="btn btn-primary" type="submit" name="submit" value="Register">
        
    </form>
</div>
{% endblock %}


{% block css-box %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
    integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'CSS/register.css' %}">
{% endblock %}