Project4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('second_hand_clothes_app/', include('second_hand_clothes_app.urls', namespace='second_hand_clothes_app')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

second_hand_clothes_app/urls.py
from django.urls import path
from . import views
app_name = 'second_hand_clothes_app'
urlpatterns = [
    #clothes views
    path('', views.clothes_index, name="clothes_index"),
    path('list/', views.clothes_list, name="clothes_list"),
    path('list/sort_by_price', views.clothes_sort, name="clothes_sort"),
    path('list/add_comment', views.clothes_add_comment, name="clothes_add_comment"),
    path('list/delete_comment', views.clothes_delete_comment, name="clothes_delete_comment"),
    path('list/<int:item_id>', views.clothes_detail, name="clothes_detail"),
    path('list/<int:item_id>/edit', views.clothes_edit, name="clothes_edit"),
    path('list/<int:item_id>/delete', views.clothes_delete, name="clothes_delete"),
    path('add_item/', views.clothes_add_item, name="clothes_add_item"),
    path('search_result/', views.clothes_search_result, name="clothes_search_result"),
    path('sign_in/', views.clothes_sign_in, name="clothes_sign_in"),
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    #clothes views
    path('register', views.register, name="register"),
    path('profile/<str:username>', views.profile, name="profile"),
    path('edit_profile/<str:username>', views.edit_profile, name="edit_profile"),
    path('sign_in_action', views.login_user, name="sign_in"),
    path('log_out/', views.logout_user, name="log_out"),
]

second_hand_clothes_app/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class ClothesList(models.Model):
    name = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='image/')
    price = models.IntegerField(default=0)
    seller = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    size = models.CharField(max_length=200)
    comment = ArrayField(models.TextField(blank=True), blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('second_hand_clothes_app:clothes_detail', args=[self.id])

regular_user = {"username": "regular", "password": "regular"}
admin_user = {"username": "admin", "password": "admin"}

        
    

second_hand_clothes_app/views.py
from django.shortcuts import render, redirect
from .models import regular_user, admin_user, ClothesList, User
from django.http import JsonResponse
from django.contrib import messages
from actions.models import Action
from comments.models import Comment
from django.core import serializers
from django.urls import reverse
from django.contrib.humanize.templatetags.humanize import naturaltime

# Create your views here.
def clothes_index(request):
    clothes = ClothesList.objects.all()
    actions = Action.objects.all().order_by('-created_time')
    return render(request,"second_hand_clothes_app/clothes/index.html", {'clothes': clothes, 'actions':actions})

def clothes_list(request):
    clothes = ClothesList.objects.all()
    
    context = {'clothes': clothes}
    return render(request,"second_hand_clothes_app/clothes/list.html", context) 

def clothes_sort(request):
    clothes = ClothesList.objects.all().order_by('price')
    
    context = {'clothes': clothes, 'order_by': 'price'}
    return render(request,"second_hand_clothes_app/clothes/list.html", context) 

def clothes_detail(request, item_id):
    clothes = ClothesList.objects.all()
    for clothes_item in clothes:
        if clothes_item.id == item_id:
            break
    user = User.objects.get(username=clothes_item.seller)
    username = request.session.get("username")
    comments = Comment.objects.all().filter(user_id=user.id).order_by('-created_time')
    return render(request,"second_hand_clothes_app/clothes/detail.html", {"clothes_item":clothes_item, "comments":comments}) 

def clothes_add_item(request):

    if request.method == 'POST':
        name = request.POST.get('name')
        picture = request.FILES.get('image')
        size = request.POST.get('size')
        price = request.POST.get('price')
        des = request.POST.get('description')

        user = User.objects.get(username=request.session.get("username"))

        cl = ClothesList(
            name = name,
            seller = request.session.get('username'),
            picture = picture,
            size = size,
            price = price,
            description = des,
            comment = [],
            user=user,
        )
        cl.save()

        #log the action
        action = Action(
            user = user,
            verb = "create the item",
            target = cl,
        )
        action.save()

        messages.add_message(request, messages.SUCCESS, "You successfully submitted the clothes: %s" % cl.name)
        return redirect('second_hand_clothes_app:clothes_detail', cl.id)
    else:
        return render(request,"second_hand_clothes_app/clothes/add_item.html")

def clothes_edit(request, item_id):
    if request.method == 'POST':
        name = request.POST.get('name')
        picture = request.FILES.get('image')
        size = request.POST.get('size')
        price = request.POST.get('price')
        des = request.POST.get('description')
        user = User.objects.get(username=request.session.get("username"))

        try:
            clothes = ClothesList.objects.get(pk=item_id)
            clothes.name = name
            clothes.size = size
            clothes.price = price
            clothes.description = des
            if picture:
                clothes.picture = picture
            clothes.save()

            #log the action
            action = Action(
                user = user,
                verb = "edit the item",
                target = clothes,
            )
            action.save()

            messages.add_message(request, messages.INFO, "You successfully edited the clothes: %s" % clothes.name)
            return redirect('second_hand_clothes_app:clothes_detail', clothes.id)
        except ClothesList.DoesNotExist:
            return redirect('second_hand_clothes_app:clothes_index')
    else:
        clothes = ClothesList.objects.all()
        for item in clothes:
            if item.id == item_id:
                break
        return render(request,"second_hand_clothes_app/clothes/edit.html", {"item": item})

def clothes_delete(request, item_id):
    user = User.objects.get(username=request.session.get("username"))
    clothes = ClothesList.objects.get(pk=item_id)
    ClothesList.objects.get(pk=item_id).delete()
    action = Action(
        user = user,
        verb = "delete the item",
        target = clothes,
    )
    action.save()
    messages.add_message(request, messages.WARNING, "You successfully deleted the clothes: %s" % clothes.name)
    return redirect('second_hand_clothes_app:clothes_list')



# def clothes_show_comment(request):
#     is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
#     if is_ajax and request.method == "POST":
#         clothes_id = request.POST.get('clothes_id')
#         clothes = ClothesList.objects.get(pk=clothes_id)
        # user = User.objects.get(username=clothes.seller)
        # try:
        #     comments_json = serializers.serialize("json", Comment.objects.all().filter(user_id=user.id))
        #     username = request.session.get("username")
        #     url = reverse('users:profile', args=[username])

        #     return JsonResponse({'success': 'success', 'comment': comments_json, 'url': url}, status=200)
        # except ClothesList.DoesNotExist:
        #     return JsonResponse({'error': 'No clothes found with that ID'}, status=200)
#     else:
#         return JsonResponse({'error': 'Invalid Ajax request'}, status=400)

def clothes_add_comment(request):
    user1 = User.objects.get(username=request.session.get("username"))
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        clothes_id = request.POST.get('clothes_id')
        clothes_comment = request.POST.get('clothes_comment')
        clothes = ClothesList.objects.get(pk=clothes_id)
        user = User.objects.get(username=clothes.seller)
        if clothes_comment != "":
            try:
                # clothes = ClothesList.objects.get(pk=clothes_id)
                cm = Comment(
                    user = user,
                    comment = clothes_comment,
                    username = request.session.get("username"),
                )
                cm.save()

                action = Action(
                    user = user1,
                    verb = "add a comment to the item",
                    target = clothes,
                )
                action.save()
                url = reverse('users:profile', args=[request.session.get("username")])
                time = naturaltime(cm.created_time)

                return JsonResponse({'success': 'success', 'comment': clothes_comment, 'url': url, 'username': request.session.get("username"), 'time':time, 'id': cm.id}, status=200)
            except ClothesList.DoesNotExist:
                return JsonResponse({'error': 'No clothes found with that ID'}, status=200)
        else:
            return JsonResponse({'error': 'No comment'}, status=200)    
    else:
        return JsonResponse({'error': 'Invalid Ajax request'}, status=400)

def clothes_delete_comment(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    if is_ajax and request.method == "POST":
        comment_id = request.POST.get('comment_id')
        comment = Comment.objects.get(pk=comment_id)
        try:
            comment.delete()
            return JsonResponse({'success': 'success', 'id': comment_id}, status=200)
        except Comment.DoesNotExist:
            return JsonResponse({'error': 'No clothes found with that ID'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid Ajax request'}, status=400)


def clothes_search_result(request):
    return render(request,"second_hand_clothes_app/clothes/search-results.html")

def clothes_sign_in(request):
    return render(request,"second_hand_clothes_app/clothes/sign_in.html")

templates/second_hand_clothes_app/clothes/add_item.html
{% extends "second_hand_clothes_app/base.html" %}
{% load static %}
{% block page-title %} Add Item Page {% endblock %}


{% block content %}

{% if request.session.username %}
<h3>Create item</h3>
<form id="form-box" action="{% url 'second_hand_clothes_app:clothes_add_item' %}" method="POST" enctype="multipart/form-data">
    <div class="form-item" id="form-name">
        <label for="name">Name* :</label><br>
        <input class="name-price" id="name" type="text" name="name" required>
    </div><!-- #form-item -->
    <!-- <div class="form-item" id="check-women">
        <p>Group:
        <p><br>
        <div class="checkbox-box">
            <div class="checkbox-item">
                <input type="checkbox" id="women" name="women">
                <label class="check-label" for="women"> Women</label>
            </div>
            <div class="checkbox-item">
                <input type="checkbox" id="men" name="men">
                <label id="check-label" for="men"> Men</label>
            </div>
        </div>
    </div>
    <div class="form-item" id="check-top">
        <p>Kind:
        <p><br>
        <div class="checkbox-box">
            <div class="checkbox-item">
                <input type="checkbox" id="top" name="top">
                <label class="check-label" for="top">Top</label>
            </div>
            <div class="checkbox-item">
                <input type="checkbox" id="bottom" name="bottom">
                <label class="check-label" for="bottom"> Buttom</label>
            </div>
        </div>
    </div> -->
    <div class="form-item" id="form-size">
        <label for="size">Size* :</label><br>
        <input class="name-price" type="text" name="size" id="size" required><br>
    </div><!-- #form-item -->
    <div class="form-item">
        <label for="photo">Photo* :</label>
        <input type="file" id="image" name="image" accept="image/*" required>
    </div><!-- #form-item -->
    <div class="form-item" id="form-price">
        <label for="price">Price* :</label><br>
        <input class="name-price" type="text" name="price" id="price" required>
    </div><!-- #form-item -->
    <div class="form-item" id="form-des">
        <label for="description">Description :</label><br>
        <input class="des-box" type="text" name="description" id="description"><br>
    </div><!-- #form-item -->
    <div id="submit-button">
        <button id="submit">Submit</button>
    </div>
    {% csrf_token %}

</form>
{% else %}
<div id="create-box">
    <h3>Create item</h3>
    <div id="warn-box">
        <p>Not a member? <a href="{% url 'users:register' %}">Register</a> to be a member and <a
                href="{% url 'second_hand_clothes_app:clothes_sign_in' %}">Sign In</a> to sell your items.</p>
    </div>
</div><!-- #create-box -->
{% endif %}


{% endblock %}


{% block css-box %}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/add_item.css' %}">
{% endblock %}

templates/second_hand_clothes_app/clothes/detail.html
{% extends "second_hand_clothes_app/base.html" %}
{% load static %}
{% block page-title %} Detail Page {% endblock %}
{% load humanize %}



{% block content %}
<a href="{% url 'second_hand_clothes_app:clothes_list' %}"><img class="left-arrow"
        src="{% static 'pictures/left.svg' %}" alt="left arrow"></a>
<div id="image-box">
    <img src="{{ clothes_item.picture.url }}" alt="item">
</div><!-- #image-box -->

<div id="item-box">
    <h3>{{clothes_item.name}}</h3>
    <p id="price"> ${{clothes_item.price}}</p>
    <p>Size : {{clothes_item.size}}</p>
    <p>Sold by : <a href="{% url 'users:profile' clothes_item.user.username %}">{{clothes_item.seller}}</a></p>
    <button id="add_cart">Add To Cart</button>
    {% if request.session.username %}
    <a href="{% url 'second_hand_clothes_app:clothes_edit' clothes_item.id %}">
        <button class="btn btn-secondary">Edit</button>
    </a>
    {% if request.session.role == "admin" %}
    <a href="{% url 'second_hand_clothes_app:clothes_delete' clothes_item.id %}">
        <button class="btn btn-danger" id="delete">Delete</button>
    </a>
    {% endif %}
    {% endif %}
</div><!-- #item-box -->
<div id="des-box">
    <h3>Description</h3>
    <p>{{clothes_item.description}}</p>
</div><!-- #description-box -->

<div id="comment-box">
    <h3>Comments About the Seller</h3>
    <div id="comment-content" data-ajax-url="{% url 'second_hand_clothes_app:clothes_delete_comment' %}">
        
        {% if comments %}
        {% for comment in comments %}
        <div class="show-comments">
            
            {% if request.session.role == "regular" %}
            
            {% if comment.username == request.session.username %}
            <p><a href="{% url 'users:profile' comment.username %}">{{comment.username}}</a>: {{comment.comment}}</p>
            <p>{{comment.created_time | naturaltime}}</p>
            <button id="comment-delete" comment-id="{{comment.id}}" data-ajax-url="{% url 'second_hand_clothes_app:clothes_delete_comment' %}">Delete</button>
            {% else %}
            <p><a href="{% url 'users:profile' comment.username %}">{{comment.username}}</a>: {{comment.comment}}</p>
            <p>{{comment.created_time | naturaltime}}</p>
            {% endif %}
            
            {% endif %}

            
            {% if request.session.role == "admin" %}
            <p><a href="{% url 'users:profile' comment.username %}">{{comment.username}}</a>: {{comment.comment}}</p>
            <p>{{comment.created_time | naturaltime}}</p>
            <button id="comment-delete" comment-id="{{comment.id}}" data-ajax-url="{% url 'second_hand_clothes_app:clothes_delete_comment' %}">Delete</button>
            {% endif %}

        </div>
        {% endfor %}

        {% else %}
        <div class="no-comment">
            <p>No comment.</p>
        </div>
            
        {% endif %}
            
        
        
            
    </div>
    
    {% if request.session.username %}
    <input id="comment-input" type="text" placeholder="leave a comment ....">
    <button id="comment-button" data-clothes-id="{{clothes_item.id}}" data-ajax-url="{% url 'second_hand_clothes_app:clothes_add_comment' %}">Submit</button>
    {% endif %}
        
</div><!-- #comment-box -->

{% endblock %}

{% block css-box %}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/detail.css' %}">
{% endblock %}

templates/second_hand_clothes_app/clothes/edit.html
{% extends "second_hand_clothes_app/base.html" %}
{% load static %}
{% block page-title %} edit Page {% endblock %}


{% block content %}
<h3>Edit item</h3>
<form id="form-box" action="{% url 'second_hand_clothes_app:clothes_edit' item.id %}" method="POST" enctype="multipart/form-data">
    <p> * = required</p>
    <div class="form-item" id="form-name">
        <label for="name">Name* :</label><br>
        <input class="name-price" id="name" type="text" name="name" value="{{item.name}}" required>
    </div><!-- #form-item -->
    <!-- <div class="form-item" id="check-women">
        <p>Group*:
        <p><br>
        <div class="checkbox-box"> 
            <div class="checkbox-item">
                <input type="checkbox" id="women" name="women">
                <label class="check-label" for="women"> Women</label>
            </div>
            <div class="checkbox-item">
                <input type="checkbox" id="men" name="men">
                <label id="check-label" for="men"> Men</label>
            </div>
        </div>
    </div>
    <div class="form-item" id="check-top">
        <p>Kind*:
        <p><br>
        <div class="checkbox-box">
            <div class="checkbox-item">
                <input type="checkbox" id="top" name="top">
                <label class="check-label" for="top">Top</label>
            </div>
            <div class="checkbox-item">
                <input type="checkbox" id="bottom" name="bottom">
                <label class="check-label" for="bottom"> Buttom</label>
            </div>
        </div>
    </div> -->
    <div class="form-item" id="form-size">
        <label for="size">Size* :</label><br>
        <input class="name-price" type="text" name="size" id="size" value="{{item.size}}" required><br>
    </div><!-- #form-item -->
    <div class="form-item">
        <label for="photo">Photo :</label>
        <img class="item-image" src="{{item.picture.url}}" alt="item">
        <input type="file" id="image" name="image" accept="image/*">
    </div><!-- #form-item -->
    <div class="form-item" id="form-price">
        <label for="price">Price* :</label><br>
        <input class="name-price" type="text" name="price" id="price" value="{{item.price}}" required>
    </div><!-- #form-item -->
    <div class="form-item" id="form-des">
        <label for="description">Description :</label><br>
        <input class="des-box" type="text" name="description" id="description" value="{{item.description}}"><br>
    </div><!-- #form-item -->
    <div id="submit-button">
        <button id="submit">Save</button>
    </div>
    {% csrf_token %}
</form>
{% endblock %}


{% block css-box %}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/edit.css' %}">
{% endblock %}

templates/second_hand_clothes_app/clothes/index.html
{% extends "second_hand_clothes_app/base.html" %}
{% load static %}
{% block page-title %} Index Page {% endblock %}


{% block content %}

{% if request.session.username %}
<div class="container dashboard">
    <div class="row">
        <div class="col-sm-12 col-md-6 dash-col">
            <h1>Welcome to your dashboard, <strong>{{request.session.username}}</strong></h1>
            {% for item in clothes %}
            <div class="container py-2 item-container">
                <div class="row">
                    <div class="col-4">
                        <img src="{{ item.picture.url }}" alt="item">
                    </div>
                    <div class="col-5">
                        <h4>{{item.name}}</h4>
                        <h4 class="item-price">${{item.price}}</h4>
                    </div>
                    <div class="col-3">
                        <a href="{% url 'second_hand_clothes_app:clothes_edit' item.id %}">
                            <button class="btn btn-secondary">Edit</button>
                        </a>
                        {% if request.session.role == "admin" %}
                        <a href="{% url 'second_hand_clothes_app:clothes_delete' item.id %}">
                            <button class="btn btn-danger" id="delete" data-toggle="modal" data-target="#Modal">Delete</button>
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-sm-12 col-md-6">
            {% include 'actions/action/feed.html' %}
        </div>
    </div>

</div>
{% else %}
<div id="idea-box">
    <img src="{% static 'pictures/item1.png' %}" alt="item1">
    <h1>Daily</h1>
</div>
<div id="idea-box2">
    <img src="{% static 'pictures/item2.png' %}" alt="item2">
    <h1>Save Earth</h1>
</div>
{% endif %}

<div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Delete</h5>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure to delete the item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    Cancell
                </button>
                <button type="button" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block css-box %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
    integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'CSS/home.css' %}">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.bundle.min.js"></script>
{% endblock %}

templates/second_hand_clothes_app/clothes/list.html
{% extends "second_hand_clothes_app/base.html" %}
{% load static %}
{% block page-title %} List Page {% endblock %}



{% block content %}
<ul id="kind-nav">
    <li><a href="#">Top</a></li>
    <li><a href="#">Bottom</a></li>
</ul><!-- #nkind-nav -->

<a href="{% url 'second_hand_clothes_app:clothes_sort' %}">
    <button class="sort-price" id="sort">Sort by Price</button>
</a>

<div id="item-list">
    
    {% if clothes %}
        {% for item in clothes %}
        <div class="item-box">
            <a href="{% url 'second_hand_clothes_app:clothes_detail' item.id %}">
                <img src="{{ item.picture.url }}" alt="item">
            </a>
            <h4>{{item.name}}</h4>
            <p>Sold by: <a href="{% url 'users:profile' item.user.username %}">{{item.user.username}}</a></p>
            <p class="item-price">${{item.price}}</p>
        </div>
        {% endfor %}
    {% else %}
        <h1>There are no clothes right now.</h1>
    {% endif %}
        
    
</div>
{% endblock %}

{% block css-box %}
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/list.css' %}">
{% endblock %}

templates/second_hand_clothes_app/clothes/search-results.html
{% extends "second_hand_clothes_app/base.html" %}
{% load static %}
{% block page-title %} Search Results Page {% endblock %}



{% block content %}
<div class="result-box">
    <h3>3 Results</h3>
    <!-- #result-box -->
</div>

<div id="item-list">
    <div class="item-box">
        <a href="detail.html">
            <img src="{% static 'pictures/item4.png' %}" alt="item4">
        </a>
        <h4>Hokies Logo Hoodie</h4>
        <p>Sold by: <a href="#">Iris Chang (10)</a></p>
        <p class="item-price">$20</p>
    </div><!-- #item -->

    <div class="item-box">
        <img src="{% static 'pictures/item1.png' %}" alt="item1">
        <h4>VT Logo Hoodie</h4>
        <p>Sold by: <a href="#">Tina (20)</a></p>
        <p class="item-price">$20</p>
    </div><!-- #item -->

    <div class="item-box">
        <img src="{% static 'pictures/item2.png' %}" alt="item2">
        <h4>VT Logo Hoodie Red</h4>
        <p>Sold by: <a href="#">Sharon (30)</a></p>
        <p class="item-price">$20</p>
    </div><!-- #item -->
</div><!-- #item-list -->
{% endblock %}


{% block no-result %}
<div class="no-result">
    <h1 class="no-result-sentence">Sorry, no result.</h1>
</div>
{% endblock %}


{% block css-box %}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/search-result.css' %}">
{% endblock %}

templates/second_hand_clothes_app/clothes/sign_in.html
{% extends "second_hand_clothes_app/base.html" %}
{% load static %}
{% block page-title %} Sign In Page {% endblock %}

<!-- {% block login-box %}
<img id="bar" src="{% static 'pictures/bar.svg' %}" alt="bar">
<img id="search-image" src="{% static 'pictures/search.svg' %}" alt="search">
<form class="search-form" action="{% url 'second_hand_clothes_app:clothes_search_result' %}" method="GET">
    <input class="search-input" type="text" id="search" name="search-clothes" placeholder="Search clothes">
    <input class="go-button" type="submit" name="search" value="Go">
</form>
<img src="{% static 'pictures/cart.png' %}" alt="cart">
<a href="{% url 'users:register' %}">Register </a>
<a href="{% url 'second_hand_clothes_app:clothes_sign_in' %}">log In</a>
{% endblock %} -->

{% block content %}
<div class="container my-5 signin">
    <h2>Sign In</h2>
    <form action="{% url 'users:sign_in' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}


{% block css-box %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
    integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'CSS/sign_in.css' %}">
{% endblock %}